version: '3'
services:
  # Nginx
  nginx:
    image: vahminator/bitmedia:0.0.1
    container_name: nginx_bitmedia
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    # В целом, у нас все конфиги уже есть в имидже. но если нужно дополнительно прокидывать данные
    volumes:
        - ./:/var/www
        - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - bitmedia_lan

networks:
  bitmedia_lan:
    driver: bridge